### ISSUE TITLE
window-list-item-demands-attention

### ISSUE THREAD

**Issue by ikuria** [zagortenay333/numix-cinnamon#10]
sry but there is something wrong, first the border-image urls are 
panel-top-item-attention.svg not attention.svg (same for hover)

i just putted 
.window-list-item-demands-attention {
         background-gradient-start: rgba(255,52,52,0.5);
	 background-gradient-end: rgba(255,144,144,0.5);
}
before the 2 css lines to check that, and it worked

**Comment by zagortenay333** [comment]
Fixed with 361a4abf3847703eb234c3cb60b55662c2dd1b3d
