### ISSUE TITLE
wrong padding @ .datemenu-date-label

### ISSUE THREAD

**Issue by ikuria** [zagortenay333/numix-cinnamon#11]
http://i.imgur.com/Baqt6LS.png
before after
for applet "World Clock Calendar" the padding is not correct like in default Theme

.datemenu-date-label {
  padding: .4em 1.75em;
  /* padding: .7em 0 .4em 0;  */
  font-size: 10pt;
  font-weight: bold;
  text-align: center;
  color: rgba(255, 255, 255, 0.8);
}

**Comment by zagortenay333** [comment]
Thx will fix soon.

**Comment by zagortenay333** [comment]
Fixed with 0995146f896429463cdd1687ea015f835b55ae68
