### ISSUE TITLE
Notification Popup & Notification Applet Issues

### ISSUE THREAD

**Issue by BadCabbage** [zagortenay333/numix-cinnamon#12]
The album art in the popup notification from rhythmbox was being stretched horizontally. I seem to have fixed it by adding this code to the !Notifications section.
![screenshot from 2015-12-26 21 14 22](https://cloud.githubusercontent.com/assets/16447344/12007968/0da0f6ac-ac16-11e5-8a6a-2273baa1d950.png)

.notification-with-image {
  min-height: 159px;
}

There was also a green line appearing on the left of the notification popup in the notification applet. Again I seem to have fixed this by replacing all the code in the !Notification applet section with:
![screenshot from 2015-12-26 21 14 00](https://cloud.githubusercontent.com/assets/16447344/12007969/1566d050-ac16-11e5-9925-f562cf946cd1.png)
.notification-applet-padding {

  padding: 0.6em 0.4em;
}

.notification-applet-padding:first-child {
  padding-top: 1.3em;
}

.notification-applet-padding:last-child {
  padding-bottom: .5em;
}

/* Notifs look inside the notification applet & other popups. */
.popup-menu-content #notification {
  border-image: url("background-assets/dark-bg.svg") 7;
  padding: 12px;
}

**Comment by zagortenay333** [comment]
Yeah, I removed that 159px hack forgetting about this. Will add it back.

The green line is intentional. Notifications get a color marker based on what type they are.

**Comment by zagortenay333** [comment]
Fixed with d47e9cbb4339a825fdb39fe6e76f64371265ae44
