### ISSUE TITLE
Cinnamon 3.0 is out

### ISSUE THREAD

**Issue by alexfrancavilla** [zagortenay333/numix-cinnamon#14]
http://segfault.linuxmint.com/2016/04/cinnamon-3-0-released/

It would be cool if the author could look into 3.0 to check if any changes to this theme are needed. A quick smoketest went smooth, but I haven't checked everything out yet.

**Comment by zagortenay333** [comment]
I think I only need to fix the sliders, but I'll wait 'till mint 18 is released.

**Comment by swifthand** [comment]
Mint 18 is out, I will install it as-is and report any issues, but is there any plan to update the package specifically for Cinnamon 3.0?

**Comment by zagortenay333** [comment]
@swifthand There is nothing to update. :confused:

I'll wait 'till cinna `3.0`. Then I'll have to do quite a bit of work I think (vertical panels and such.) Will also skip any other updates 'till then like refactoring and updating the theme to match the GTK version.

**Comment by swifthand** [comment]
@zagortenay333 Understood. 

I didn't see anything wrong with the theme when I used it, but I figured that you, as its author, would have a better sense for anything I might overlook.

**Comment by UntilSunrise** [comment]
@zagortenay333 3.2 is out, did you start working on it?

**Comment by zagortenay333** [comment]
@UntilSunrise Where did you read that it is released?

**Comment by UntilSunrise** [comment]
@zagortenay333 https://github.com/linuxmint/Cinnamon/releases

**Comment by morph027** [comment]
No packages yet except nightly ppa (which does not work for me here). Right now i'm building packages for xenial. When ready, i'll provide a link, if you need them.

**Comment by morph027** [comment]
http://download.morph027.de/cinnamon-3.2.0/

**Comment by zagortenay333** [comment]
I'll wait till mint 18.1 is released.

**Comment by lburgazzoli** [comment]
Any chance to have a look earlier ?  :-)
cinnamon has been upgraded to 3.2 in Fedora 25 and it does not looks very nice

**Comment by zagortenay333** [comment]
@lburgazzoli Nah, srry. You're gonna have to wait till mint 18.1. :smile:

**Comment by zagortenay333** [comment]
Should be out in December apparently.

**Comment by lburgazzoli** [comment]
I can wait :-)
Btw, have you never taken into account the possibility to contribute it to official numix repo ?

**Comment by zagortenay333** [comment]
Never crossed my mind tbh. I'm probably way too selfish for that XD.

**Comment by lburgazzoli** [comment]
Mint Cinnamon 18.1 has been released :-)
http://blog.linuxmint.com/?p=3181

**Comment by zagortenay333** [comment]
@lburgazzoli Nice. Thx for the heads up.

**Comment by zagortenay333** [comment]
> It will also be possible to upgrade from Linux Mint 18. Upgrade instructions will be published later this month.

Lol

**Comment by zagortenay333** [comment]
I was hoping to upgrade rather than install from scratch..

**Comment by lburgazzoli** [comment]
I remember reinstall everything was the recommended path some time ago ... but I do not know now as I've switched distro

**Comment by swifthand** [comment]
Throughout the 17.X era the upgrade process between versions went smoothly for me.

However, I performed a full reinstall for upgrading from 17.3 to 18.0 as it just seemed like a good idea.

**Comment by zagortenay333** [comment]
I'm trying to upgrade from 18.0 to 18.

**Comment by fllp** [comment]
@zagortenay333: Could i maybe help updating?  
I think i've managed to update all the necessary components and could open a PR.

**Comment by zagortenay333** [comment]
Please don't. I have a specific idea of what I want to do. Two themes are already updated, third is almost finished, and three more to go.
I'll do numix last 'cause I need to actually update the whole thing to match with the GTK theme.

**Comment by zagortenay333** [comment]
You can already see it in my Secunda and Tertia themes. Lots of file structure changes, replacing gulpfile with a bash script, and other stuff with the scss.

**Comment by fllp** [comment]
i just did. should have done that before forking this, would've spared me the meddle with gulp ;)

**Comment by zagortenay333** [comment]
Yeah bash is much nicer, but installing sassc is surprisingly difficult.. Took me a while to figure it out..

**Comment by zagortenay333** [comment]
Even the instructions on the github repo are faulty and nobody bothers to fix it. Dafuq. :disappointed:

**Comment by zagortenay333** [comment]
Finished!
