### ISSUE TITLE
Scroll bar button hard to see

### ISSUE THREAD

**Issue by alexkieling** [zagortenay333/numix-cinnamon#15]
I find the scroll bar button hard to see due to not being very different to the color of the scroll bar. When selected, the button changes to red and is easily visible. I would like to suggest the use of a color similar to the one used when the button is selected. Does that make sense?

**Comment by zagortenay333** [comment]
This theme will be completely redesigned for the next cinnamon release (hopefully.) 'Till then, you're gonna have to live with it. :smile:

**Comment by alexkieling** [comment]
No problem. It's already great the way it is. Good job!
