### ISSUE TITLE
Linux Mint 18.1 Bug

### ISSUE THREAD

**Issue by szekeres2016** [zagortenay333/numix-cinnamon#16]
After updating Linux Mint 18 to 18.1 the theme looks broken. Gui elements for tray applications and the Mint menu looks like this now, can you please update the theme with fixes?
![kepernyokep 2016-12-25 16-42-09](https://cloud.githubusercontent.com/assets/20751590/21471897/8f19556e-cac2-11e6-9e51-f64a13959e20.png)

**Comment by zagortenay333** [comment]
It's already pointed out... #14 

Working on it.
