### ISSUE TITLE
Missaligned text

### ISSUE THREAD

**Issue by szekeres2016** [zagortenay333/numix-cinnamon#17]
First of all thank you for the quick update on the theme, I really like the new mint menu icons are very cool. I noticed a little bug though. As you can see on the attached screenshot the mint menu texts are rendering a bit too low compared to the previous versions. The bottom of the letters are outside of the menu area. If this little bug could be fixed I would be really happy, thank you, and happy new year!
![kepernyokep 2017-01-04 13-33-19](https://cloud.githubusercontent.com/assets/20751590/21644140/569b7efc-d28c-11e6-817a-6969a07c6293.png)

**Comment by zagortenay333** [comment]
Should be better now, but it's a bug with the actual menu applet.

I opened an issue: https://github.com/linuxmint/Cinnamon/issues/6167

**Comment by zagortenay333** [comment]
@szekeres2016 Has this been solved?

**Comment by szekeres2016** [comment]
Yes, thank you it looks perfect now! :)

**Comment by zagortenay333** [comment]
:smile:
