### ISSUE TITLE
[Restructure/3.2 Update] Orientation of panel assets switched

### ISSUE THREAD

**Issue by fllp** [zagortenay333/numix-cinnamon#18]
The highlighting for the selected window in the assets has moved to the opposite side 
(e.g. top edge instead of bottom for top panel).

![active window](https://cloud.githubusercontent.com/assets/15898292/21689323/4cfb2994-d370-11e6-93d8-36055944a54e.png)

Is that intentional?

**Comment by zagortenay333** [comment]
Yes it's intentional.

**Comment by zagortenay333** [comment]
Srry if you don't like it that way :confused:

**Comment by fllp** [comment]
I see.  I just thought maybe there was a mishap when renaming the assets for the restructuring.  
Nevermind, there is this „mirror” button in Inkscape that will fix it for me ;)

**Comment by zagortenay333** [comment]
:smile:
