### ISSUE TITLE
Calendar applet

### ISSUE THREAD

**Issue by azapletal** [zagortenay333/numix-cinnamon#2]
Week numbers (if enabled) in calendar applet aren't displayed properly. Ellipses instead. 
[Edit] If I reduce font-size in .calendar-week-number from 8pt to 7pt it works. So maybe you should vary the width/height  to keep 8pt (?)

Great theme anyway :) Thx.

**Comment by zagortenay333** [comment]
I didn't have this issue. Anyway, I edited the calendar to use em's instead of pixels for widths and heights in certain places. Now you should be able to set any font size to week numbers.

**Comment by azapletal** [comment]
Well, I digged a bit deeper.
Main reason was that I didn't have 'Droid Sans'  installed on the system. ('DejaVu Sans Book' as standard sans-serif here. For this your new 1.2em width is still not sufficient, needed about 1.3em ).

Now with Droid everything's fine :)

**Comment by zagortenay333** [comment]
The real issue here are these freakin fixed widths and height's. No em 's will fix this. I'll see that I replace them with  min/max.

This can be closed now.
