### ISSUE TITLE
No input field for search in menu / huge icon vs small text

### ISSUE THREAD

**Issue by rubin55** [zagortenay333/numix-cinnamon#23]
Just installed Numix-Cinnamon and enabled it from the Cinnamon Themes menu. I'm running Cinnamon 3.0.1 on Gentoo, on HiDPI (192DPI). It looks great! Just one strange issue with the search input field on the "start" menu. See screenshots.

* See here with a huge icon indicating the searchbox location (just above "All Applications"):
![strange search input in menu](https://cloud.githubusercontent.com/assets/6214491/24619611/d6645b3c-189a-11e7-90af-93591453ee23.png)

* Here with some text in the search box: 
![strange search input now with some text](https://cloud.githubusercontent.com/assets/6214491/24619617/dc6d9f84-189a-11e7-8244-b593d7fe5e4a.png)

**Comment by zagortenay333** [comment]
The master branch is for cinna `3.2`. For older versions you need to download one of the releases.

**Comment by zagortenay333** [comment]
Is this fixed?

**Comment by rubin55** [comment]
Yes, running with the V2.8--v3.0 tag as we speak, looks amazingly nice! :)

**Comment by zagortenay333** [comment]
Cheers.
