### ISSUE TITLE
Question: Dark Window Theme

### ISSUE THREAD

**Issue by jaypanares** [zagortenay333/numix-cinnamon#3]
Excellent theme.  I can't seem to get the same dark windows your screenshots in deviant art have.  Is this another thing I have to install/configure?  When I used this theme in Mint theme settings, only the application bar changed to the dark theme.  Thanks! (Linux noob here)

**Comment by zagortenay333** [comment]
This is only a cinnamon. For windows, you need to install the GTK theme.
