### ISSUE TITLE
Error when trying to add theme

### ISSUE THREAD

**Issue by chasbel2112** [zagortenay333/numix-cinnamon#6]
Attempting to add the theme from the Themes menu gives the following error:

"An error occurred while trying to access the server.  Please try again in a little while.

Details:  HTTP Error 404: Not Found"

Any idea how to remedy this?

**Comment by zagortenay333** [comment]
Does it happen with other themes?

**Comment by chasbel2112** [comment]
It does not, for some reason
On 11/25/2015 08:46 AM, zagortenay333 wrote:
> Does it happen with other themes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zagortenay333/numix-cinnamon/issues/6#issuecomment-159611907>.
>

-- 
Chas Belfield
AVDENTES FORTVNA IVVAT

**Comment by zagortenay333** [comment]
Strange.. Will look into it later.

**Comment by chasbel2112** [comment]
thank you
On 11/25/2015 09:27 AM, zagortenay333 wrote:
> Strange.. Will look into it later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zagortenay333/numix-cinnamon/issues/6#issuecomment-159621968>.
>

-- 
Chas Belfield
AVDENTES FORTVNA IVVAT

**Comment by zagortenay333** [comment]
Btw, did you click the refresh button?

**Comment by chasbel2112** [comment]
now i feel stupid
thanks!
On 11/25/2015 09:56 AM, zagortenay333 wrote:
> Btw, did you click the refresh button?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zagortenay333/numix-cinnamon/issues/6#issuecomment-159631869>.
>

-- 
Chas Belfield
AVDENTES FORTVNA IVVAT

**Comment by zagortenay333** [comment]
:smile:
