### ISSUE TITLE
Keyboard Layout Applet bug

### ISSUE THREAD

**Issue by PlugaruT** [zagortenay333/numix-cinnamon#7]
When the Keyboard layout applet is enabled on panel, the scaling doesn't work correctly. 
![bug](https://cloud.githubusercontent.com/assets/6437932/11985239/43f0aa7e-a9cb-11e5-9fcc-2ea4b85bd58e.png) 
Please edit this line:
`.panel-status-button {
  height: inherit;
}`

The result:
![fixed](https://cloud.githubusercontent.com/assets/6437932/11985255/65b54e3a-a9cb-11e5-8981-7a8ef87b8262.png)

**Comment by zagortenay333** [comment]
Thx for pointing out! Feel free to make a pull if you want. Otherwise I'll fix it soon (not on cinna right now.)

I completely forgot I can use the `inherit` value here :smile:

**Comment by PlugaruT** [comment]
Ok then, I will submit a pull request soon ;)
